### ISSUE TITLE
Vulnerability report

### ISSUE THREAD

**Issue by JafarAkhondali** [warren-bank/node-serve#3]
We are a group of researchers from Leiden University, and we conduct research on vulnerabilities in open-source software. We have discovered and verified a high-severity vulnerability in your project(warren-bank/node-serve). Explaining the vulnerability further in this issue could allow malicious users to access details, so we recommend [enabling private vulnerability reporting on GitHub](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) to discuss this matter confidentially.
        After you have enabled this feature, please add a comment to this issue so we can continue our discussion. If you have any questions, feel free to leave a reply here or send an email to: j.akhoundali [at] liacs.leidenuniv.nl

**Comment by warren-bank** [comment]
@JafarAkhondali , Hello. I've enabled private vulnerability reporting for this repo. I'd be curious to hear your findings. Having said that, this project is a [fork](https://github.com/warren-bank/node-serve#fork) of a very popular project. Although I've made a ton of changes, the foundation remains shared. So, I'd also be curious to compare your finding for the two.

**Comment by JafarAkhondali** [comment]
Hi @warren-bank ,
Thanks. I've submitted the full report, let me know if you want to discuss something

**Comment by warren-bank** [comment]
Thanks again! :smiley:
